const API_URL = import.meta.env.VITE_API_URL;
const KAKAO_REST_API_KEY = import.meta.env.VITE_KAKAO_REST_API_KEY;
const KAKAO_REDIRECT_URI = import.meta.env.VITE_KAKAO_REDIRECT_URI;
const FASTAPI_URL = import.meta.env.VITE_FASTAPI_URL;

export { API_URL, KAKAO_REST_API_KEY, KAKAO_REDIRECT_URI, FASTAPI_URL };
