export const ITEMS_PER_BATCH = 9;
export const CLOSET_TABS = [
  { id: "clothes", label: "옷" },
  { id: "coordi", label: "코디" },
];
export const MAIN_CATEGORIES = [
  {
    id: "all",
    name: "전체",
    subcategories: [{ id: "all", name: "전체" }],
  },
  {
    id: "top",
    name: "상의",
    subcategories: [
      { id: "all", name: "전체" },
      { id: "shirts", name: "셔츠" },
      { id: "short-sleeve", name: "반팔티" },
      { id: "long-sleeve", name: "긴팔티" },
      { id: "knit", name: "니트" },
    ],
  },
  {
    id: "bottom",
    name: "하의",
    subcategories: [
      { id: "all", name: "전체" },
      { id: "jeans", name: "청바지" },
      { id: "slacks", name: "슬랙스" },
      { id: "skirt", name: "스커트" },
    ],
  },
  {
    id: "shoes",
    name: "신발",
    subcategories: [
      { id: "all", name: "전체" },
      { id: "sneakers", name: "스니커즈" },
      { id: "boots", name: "부츠" },
      { id: "heels", name: "힐" },
    ],
  },
  {
    id: "outer",
    name: "아우터",
    subcategories: [
      { id: "all", name: "전체" },
      { id: "coat", name: "코트" },
      { id: "jacket", name: "자켓" },
      { id: "padding", name: "패딩" },
    ],
  },
  {
    id: "fashion-item",
    name: "패션소품",
    subcategories: [
      { id: "all", name: "전체" },
      { id: "bag", name: "가방" },
      { id: "belt", name: "벨트" },
      { id: "watch", name: "시계" },
    ],
  },
];
const baseImage =
  "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80";
export const CLOTHING_ITEMS = [
  {
    id: "closet-1",
    name: "파브레가 셔츠",
    brand: "파브레가",
    size: "XL",
    price: 49500,
    purchaseDate: "2025-09-13",
    purchaseLink: "musinsa.com/products/332145",
    description:
      "파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠파란색 최애 스트라이프 셔츠",
    category: "top",
    subCategory: "shirts",
    wearCount: 5,
    lastWornDate: "2025-09-17",
    images: [baseImage],
  },
  {
    id: "closet-2",
    name: "코지 크림 니트",
    brand: "코지웨어",
    size: "L",
    price: 72000,
    purchaseDate: "2024-12-20",
    purchaseLink: "https://example.com/products/knit",
    description: "겨울에 자주 입는 크림 컬러 니트",
    category: "top",
    subCategory: "knit",
    wearCount: 12,
    lastWornDate: "2025-01-03",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
      baseImage,
    ],
  },
  {
    id: "closet-3",
    name: "라이트 블루 셔츠",
    brand: "무신사 스탠다드",
    size: "M",
    price: 38900,
    purchaseDate: "2024-08-10",
    purchaseLink: "https://example.com/products/light-blue-shirt",
    description: "구김이 적은 데일리 셔츠",
    category: "top",
    subCategory: "shirts",
    wearCount: 9,
    lastWornDate: "2024-11-28",
    images: [baseImage],
  },
  {
    id: "closet-4",
    name: "블랙 슬랙스",
    brand: "테일러",
    size: "32",
    price: 68000,
    purchaseDate: "2024-04-03",
    purchaseLink: "https://example.com/products/slacks",
    description: "미팅용으로 즐겨 입는 블랙 슬랙스",
    category: "bottom",
    subCategory: "slacks",
    wearCount: 7,
    lastWornDate: "2024-12-19",
    images: [
      "https://images.unsplash.com/photo-1489980557514-251d61e3eeb6?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-5",
    name: "라이트 데님",
    brand: "데님라운지",
    size: "30",
    price: 54000,
    purchaseDate: "2024-06-15",
    purchaseLink: "https://example.com/products/denim",
    description: "여름에 시원하게 입기 좋은 연청 데님",
    category: "bottom",
    subCategory: "jeans",
    wearCount: 4,
    lastWornDate: "2024-09-04",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-6",
    name: "화이트 스니커즈",
    brand: "클린핏",
    size: "270",
    price: 89000,
    purchaseDate: "2024-03-18",
    purchaseLink: "https://example.com/products/sneakers",
    description: "데일리로 신기 좋은 화이트 스니커즈",
    category: "shoes",
    subCategory: "sneakers",
    wearCount: 20,
    lastWornDate: "2025-01-01",
    images: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-7",
    name: "울 코트",
    brand: "클래식",
    size: "L",
    price: 168000,
    purchaseDate: "2023-11-05",
    purchaseLink: "https://example.com/products/coat",
    description: "겨울 필수템인 챠콜 울 코트",
    category: "outer",
    subCategory: "coat",
    wearCount: 3,
    lastWornDate: "2024-12-25",
    images: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-8",
    name: "블랙 백팩",
    brand: "어반팩",
    size: "Free",
    price: 99000,
    purchaseDate: "2024-02-14",
    purchaseLink: "https://example.com/products/backpack",
    description: "수납력이 좋은 블랙 백팩",
    category: "fashion-item",
    subCategory: "bag",
    wearCount: 30,
    lastWornDate: "2025-01-05",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-9",
    name: "그레이 후디",
    brand: "에브리데이",
    size: "XL",
    price: 59000,
    purchaseDate: "2024-10-11",
    purchaseLink: "https://example.com/products/hoodie",
    description: "편안한 기본 그레이 후디",
    category: "top",
    subCategory: "long-sleeve",
    wearCount: 10,
    lastWornDate: "2025-01-02",
    images: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-10",
    name: "화이트 셔츠",
    brand: "포멀라인",
    size: "L",
    price: 62000,
    purchaseDate: "2023-09-07",
    purchaseLink: "https://example.com/products/white-shirt",
    description: "포멀한 자리에서 활용하는 화이트 셔츠",
    category: "top",
    subCategory: "shirts",
    wearCount: 15,
    lastWornDate: "2024-12-31",
    images: [baseImage],
  },
  {
    id: "closet-11",
    name: "브라운 로퍼",
    brand: "클래식",
    size: "265",
    price: 110000,
    purchaseDate: "2024-05-29",
    purchaseLink: "https://example.com/products/loafer",
    description: "가죽 광이 좋은 브라운 로퍼",
    category: "shoes",
    subCategory: "boots",
    wearCount: 6,
    lastWornDate: "2024-10-22",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "closet-12",
    name: "그레이 패딩",
    brand: "윈터프루프",
    size: "L",
    price: 189000,
    purchaseDate: "2024-12-01",
    purchaseLink: "https://example.com/products/padding",
    description: "한겨울을 위한 가벼운 패딩",
    category: "outer",
    subCategory: "padding",
    wearCount: 2,
    lastWornDate: "2025-01-04",
    images: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80",
    ],
  },
];
export const COORDI_ITEMS = [
  {
    id: "coordi-1",
    name: "블루 셔츠 데님 코디",
    description: "상큼한 데일리 코디",
    images: [baseImage],
  },
];
